name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand(\"ping\").ok'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r todo-backend/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . || true

      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host localhost --eval "db.adminCommand('ping')"; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
      - name: Run tests (optional if no tests yet)
        run: pytest || echo "No tests yet"
